name: build-windows-binaries

on: [push, pull_request]

env:
  CMAKE_GENERATOR: Ninja

jobs:
  mingw-build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW64, arch: x86_64 },
          { msystem: MINGW32, arch: i686   }
        ]
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3

    - name: Setup MinGW native environment
      uses: msys2/setup-msys2@v3
      if: contains(matrix.msystem, 'MINGW')
      with:
        msystem: ${{ matrix.msystem }}
        update: false
        install: >-
          git
          mingw-w64-${{ matrix.arch }}-gcc
          mingw-w64-${{ matrix.arch }}-gcc-fortran
          mingw-w64-${{ matrix.arch }}-cmake
          mingw-w64-${{ matrix.arch }}-ninja

    - run: >-
        cmake
        -B build
        -DCMAKE_BUILD_TYPE=Release
        -DSTATIC=ON

    - name: cmake build
      run: cmake --build build --parallel

    - name: catch build fail
      run: cmake --build build --verbose --parallel 1
      if: failure()

    - name: get commit sha
      run: >
        echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

    - name: rename binary to include SHA
      run: |
        cd build
        mv HAZ.exe HAZ-$SHORT_SHA.exe
        ls

    - name: upload artifacts
      uses: 'actions/upload-artifact@v3'
      with:
        name: HAZ-${{ env.SHORT_SHA }}.exe ${{ matrix.arch }}
        path: ${{ github.workspace }}/build/HAZ-${{ env.SHORT_SHA }}.exe

